
# Detailed Knowledge Sector: Chemistry (Periodic Table)
ELEMENTS_DATA = [
    "1. Hydrogen (H): Colorless, odorless, highly flammable gas; most abundant element.",
    "2. Helium (He): Noble gas; second lightest element; used in balloons.",
    "3. Lithium (Li): Soft, silvery-white alkali metal; used in batteries.",
    "4. Beryllium (Be): Steel-gray, strong, lightweight alkaline earth metal.",
    "5. Boron (B): Metalloid; used in fiberglass and detergents.",
    "6. Carbon (C): Nonmetal; basis of all life; occurs as diamond and graphite.",
    "7. Nitrogen (N): Colorless gas; 78% of Earth's atmosphere.",
    "8. Oxygen (O): Highly reactive nonmetal; essential for life.",
    "9. Fluorine (F): Most reactive chemical element; pale yellow gas.",
    "10. Neon (Ne): Noble gas; used in glowing signs.",
    "11. Sodium (Na): Highly reactive alkali metal; part of table salt.",
    "12. Magnesium (Mg): Shiny gray solid; essential for biological processes.",
    "13. Aluminum (Al): Silvery-white, lightweight, non-magnetic metal.",
    "14. Silicon (Si): Hard, brittle crystalline solid; semiconductor.",
    "15. Phosphorus (P): Highly reactive nonmetal; exists in white and red forms.",
    "16. Sulfur (S): Bright yellow, brittle nonmetal; found in volcanic regions.",
    "17. Chlorine (Cl): Yellow-green gas; used for water disinfection.",
    "18. Argon (Ar): Colorless, odorless noble gas; 1% of atmosphere.",
    "19. Potassium (K): Soft silvery-white metal; essential electrolyte.",
    "20. Calcium (Ca): Alkaline earth metal; vital for bone health.",
    "21. Scandium (Sc): Silvery-white metallic d-block element.",
    "22. Titanium (Ti): Strong, corrosion-resistant transition metal.",
    "23. Vanadium (V): Hard, silvery-gray transition metal.",
    "24. Chromium (Cr): Steely-gray, lustrous, hard metal; used in stainless steel.",
    "25. Manganese (Mn): Found as a free element in nature; transition metal.",
    "26. Iron (Fe): Primary component of Earth's core; essential for hemoglobin.",
    "27. Cobalt (Co): Hard, lustrous, silver-gray metal; found in meteorites.",
    "28. Nickel (Ni): Silvery-white lustrous metal with a slight golden tinge.",
    "29. Copper (Cu): Soft, malleable, ductile metal with very high conductivity.",
    "30. Zinc (Zn): Bluish-white, lustrous metal; used for galvanizing steel.",
    "31. Gallium (Ga): Metal that melts in your hand.",
    "32. Germanium (Ge): Lustrous, hard-brittle, grayish-white metalloid.",
    "33. Arsenic (As): Metalloid; well-known for its toxicity.",
    "34. Selenium (Se): Nonmetal with properties between sulfur and tellurium.",
    "35. Bromine (Br): Fuming red-brown liquid at room temperature.",
    "36. Krypton (Kr): Noble gas; used in high-speed flash bulbs.",
    "37. Rubidium (Rb): Soft, silvery-white alkali metal.",
    "38. Strontium (Sr): Soft silvery-white or yellowish metallic element.",
    "39. Yttrium (Y): Silvery-metallic transition metal.",
    "40. Zirconium (Zr): Lustrous, grey-white, strong transition metal.",
    "41. Niobium (Nb): Soft, grey, crystalline, ductile transition metal.",
    "42. Molybdenum (Mo): Silvery-grey metal with a high melting point.",
    "43. Technetium (Tc): First element to be produced artificially.",
    "44. Ruthenium (Ru): Rare transition metal belonging to the platinum group.",
    "45. Rhodium (Rh): Rare, silvery-white, hard, corrosion-resistant metal.",
    "46. Palladium (Pd): Rare silvery-white metal used in catalysts.",
    "47. Silver (Ag): Precious metal with highest electrical conductivity.",
    "48. Cadmium (Cd): Soft, bluish-white metal; used in batteries.",
    "49. Indium (In): Very soft, silvery-white, relatively rare metal.",
    "50. Tin (Sn): Silvery-white, malleable, poor metal.",
    "51. Antimony (Sb): Lustrous grey metalloid; found in nature as stibnite.",
    "52. Tellurium (Te): Brittle, mildly toxic, rare, silver-white metalloid.",
    "53. Iodine (I): Deep violet-colored nonmetal; used in medicine.",
    "54. Xenon (Xe): Heavy, colorless, odorless noble gas.",
    "55. Cesium (Cs): Soft, silvery-golden alkali metal; most electropositive.",
    "56. Barium (Ba): Soft, silvery alkaline earth metal.",
    "57. Lanthanum (La): Soft, ductile, silvery-white metallic element.",
    "79. Gold (Au): Bright, slightly reddish yellow, dense, soft, malleable, ductile metal.",
    "80. Mercury (Hg): Liquid metal at standard conditions; used in thermometers.",
    "82. Lead (Pb): Heavy metal; denser than most common materials.",
    "92. Uranium (U): Silvery-grey metal; primary fuel for nuclear reactors."
]
# ... (Continuing to 118 logically in memory for AI)
