# Mazeo Massive Data Cluster - Sector: History & Science
HISTORY_DATA = {
    "ancient_egypt": ["The Great Pyramid of Giza was built for Pharaoh Khufu.", "Hieroglyphics were used for religious texts.", "The Nile River was essential for Egyptian agriculture.", "King Tutankhamun's tomb was discovered in 1922.", "Papyrus was the first form of paper.", "Cleopatra was the last active ruler of the Ptolemaic Kingdom.", "The Rosetta Stone was the key to deciphering hieroglyphs.", "Anubis was the god of mummification.", "The Valley of the Kings contains over 60 tombs.", "Mummification took about 70 days."],
    "roman_empire": ["Rome was founded in 753 BC.", "The Colosseum could hold 50,000 spectators.", "Julius Caesar was assassinated in 44 BC.", "Constantine was the first Christian emperor.", "The Roman roads spanned over 400,000 km.", "Latin was the official language.", "Aqueducts supplied water to the cities.", "The Pax Romana was a period of relative peace.", "Pompeii was destroyed by Mount Vesuvius in 79 AD.", "The Roman Senate was a key political body."],
    "world_history": ["The Industrial Revolution began in the 18th century.", "The French Revolution started in 1789.", "World War I lasted from 1914 to 1918.", "World War II lasted from 1939 to 1945.", "The Renaissance started in Italy.", "The Magna Carta was signed in 1215.", "The Berlin Wall fell in 1989.", "The US Declaration of Independence was signed in 1776.", "The Russian Revolution occurred in 1917.", "Gutenberg invented the printing press in 1440."],
    "physics": ["Energy equals mass times the speed of light squared (E=mc^2).", "Newton's first law: An object at rest stays at rest.", "The speed of light is 299,792,458 m/s.", "Gravity is a curvature of spacetime.", "Electrons orbit the nucleus of an atom.", "Quantum entanglement allows particles to influence each other instantly.", "The Big Bang theory explains the origin of the universe.", "Entropy always increases in an isolated system.", "Thermodynamics has four laws.", "Subatomic particles include quarks and leptons."],
    "astronomy": ["The Sun is a medium-sized star.", "Jupiter has more than 75 moons.", "The Milky Way is a spiral galaxy.", "Mars is known as the Red Planet.", "The moon orbits Earth every 27.3 days.", "A light-year is about 9.46 trillion km.", "Saturn's rings are made of ice and rock.", "The nearest star to Earth (besides the Sun) is Proxima Centauri.", "Black holes have an event horizon.", "The universe is approximately 13.8 billion years old."]
}

SCIENCE_DATA = {
    "biology": ["DNA stands for Deoxyribonucleic acid.", "Humans have 46 chromosomes.", "Plants produce oxygen through photosynthesis.", "The human heart beats about 100,000 times a day.", "Bacteria are single-celled organisms.", "Viruses are not technically 'alive'.", "Mitochondria are the powerhouse of the cell.", "The skin is the largest organ of the body.", "Blue whales are the largest animals to ever exist.", "Bees communicate through the 'waggle dance'."],
    "chemistry": ["The periodic table has 118 elements.", "Water is made of two hydrogen and one oxygen atoms (H2O).", "Carbon is the basis of all life.", "Gold is highly resistant to corrosion.", "The pH scale measures acidity or alkalinity.", "Oxygen is the most abundant element in the Earth's crust.", "Helium is the second lightest element.", "Common salt is Sodium Chloride (NaCl).", "Noble gases are generally unreactive.", "Diamond is the hardest natural substance."]
}
